### PR TITLE
Fix pre tag styling

### LINKED ISSUE #16: Pre blocks overflow off of the main container
image

### PR DESCRIPTION
**Pull request by jacobmischka**
Fixes #16, related to #15

### CODE REVIEW

File: components/comment.js [hunk 1]
```diff
@@ -70,9 +70,12 @@ export default class Comment extends React.Component {
         .text :global(p) {
           margin-top: 10px;
         }
-        
+
         .text :global(pre) {
           margin-bottom: 10px;
+		  max-width: 900px;
+		  overflow: auto;
+		  padding: 2px;
```
Comment (rauchg) [inline components/comment.js]: indent issue

Comment (jacobmischka) [inline components/comment.js]: whoops, thanks Atom for not copying file indent settings like you're supposed to
